#!/usr/bin/env bash

set -euo pipefail

this="${BASH_SOURCE-$0}"
this_dir=$(cd -P -- "$(dirname -- "${this}")" && pwd -P)

dirs=(
    "radar"
    "sim"
)

for d in ${dirs[@]}; do
    "${this_dir}/${d}"/scripts/run
done
