#!/usr/bin/env bash

set -euo pipefail

this="${BASH_SOURCE-$0}"
this_dir=$(cd -P -- "$(dirname -- "${this}")" && pwd -P)

tests=(
    "configurator"
)

for t in ${tests[@]}; do
    python test_${t}.py
done
