#!/usr/bin/env bash

set -euo pipefail

this="${BASH_SOURCE-$0}"
this_dir=$(cd -P -- "$(dirname -- "${this}")" && pwd -P)
data="${this_dir}/../data"
tools="${this_dir}/../../../tools"

wd=$(mktemp -d)
netcdf_dir="${wd}/netcdf"
mkdir -p "${netcdf_dir}"

tdm_grib2cf -d "${data}" -O "${netcdf_dir}" bolam 2018071300
nc_ds=$(find "${netcdf_dir}" -name '*.nc' | head -n 1)
"${tools}"/check_sim_nc "${netcdf_dir}"

rm -rf "${wd}"
