#!/usr/bin/env bash

set -euo pipefail

this="${BASH_SOURCE-$0}"
this_dir=$(cd -P -- "$(dirname -- "${this}")" && pwd -P)

tests=(
    "noaa_fetcher"
)

pushd "${this_dir}"
for t in ${tests[@]}; do
    python test_${t}.py
done
popd
